spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatgpt

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: chatgpt

ollama:
  base-url: http://localhost:11434
  model: gemma3:4b

server:
  port: 8080
